version: '3.8'

services:
  redis:
    image: redis:alpine
    env_file:
      - .env
    command: redis-server --requirepass $REDIS_PASSWORD --bind 0.0.0.0
    networks:
      - dev
    
  nginx:
    image: nginx:stable-alpine
    ports: 
      - "80:80"
      - "443:443"
    volumes:
      - './nginx.conf:/etc/nginx/nginx.conf'
      - './static:/var/www/static' 
      - '../../etc/letsencrypt/live/sendemail.space/:/etc/ssl/live'
      - '../../etc/letsencrypt/archive/sendemail.space/:/etc/ssl/archive'
    depends_on:
      - backend 
      - redis
    networks:
      - dev

  backend: 
    build: . 
    entrypoint: /entrypoint.sh
    ports: 
      - "8000:8000"
      - "5555:5555"
    volumes:
      - './db:/db'
      - './logs:/logs'
      - ./static:/var/www/static
    depends_on:
      - redis
    env_file:
      - .env
    networks:
      - dev

networks:
  dev: