# Generated by Django 5.1.3 on 2024-11-28 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ipaddress',
            name='email',
            field=models.EmailField(default='a@gmail.com', max_length=100, verbose_name='Электронная почта'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ipaddress',
            name='password',
            field=models.CharField(default='erfaiuh', max_length=50, verbose_name='Пароль приложения'),
            preserve_default=False,
        ),
    ]
