# Generated by Django 5.1.3 on 2024-11-28 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_ipaddress_email_ipaddress_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='ipaddress',
            name='host',
            field=models.CharField(default='smtp.gmail.com', max_length=100, verbose_name='SMTP-сервер'),
            preserve_default=False,
        ),
    ]
